### ISSUE TITLE
Responsive for Mobile Devices

### ISSUE THREAD

**Issue by AJKilmurray** [AJKilmurray/todo-application#1]
Make application responsive for mobile devices, and screens below 1000px width.

**Comment by AJKilmurray** [comment]
Header has now been made responsive.

```css
@media (max-width: 1000px) {
    #todo-header {
        flex-direction: column;
        align-items: center
    }

    #todo-title {
        text-align: center;
    }
}

@media (max-width: 596px) {
    #todo-input {
        width: 200px !important;
        font-size: 18px !important;
    }

    #todo-add,
    #todo-clear {
        width: 50px;
        height: 40px;
    }
}

@media (max-width: 345px) {
    #todo-input {
        width: 175px !important;
        font-size: 15px !important;
    }
}
```
